services:
  # Backend API Service
  - type: web
    name: hubtransfer-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_USER
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_PORT
        value: 5432
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false

  # Frontend Static Site
  - type: static
    name: hubtransfer-frontend
    staticPublishPath: ./frontend
    buildCommand: echo "No build needed for static files"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
